site_name: My Docs
site_author: pioordoz

# Configuration
theme: 
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    
     
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


# Extensions

markdown_extensions:
  - tables
  - md_in_html
  - attr_list
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

# Page tree

nav:
  - Home: index.md
  - Niveis: 
    - Niveis: niveis.md